### ISSUE TITLE
Battery Level reporting steps

### ISSUE THREAD

**Issue by alienatedsec** [ctvedt/esphome#1]
https://github.com/ctvedt/esphome/blob/e7939bce243c84413f6f290c8e98dbbcebb0b517/IP5306.h#L21-L24

Wondering if you managed to extend the range of reported battery levels (?)

**Comment by ctvedt** [comment]
IP5306 only reports these 4 states unfortunately. I believe there are mainly used for leds to indicate the battery level using 4 leds.
